//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vat.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableVat
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string CheckNo { get; set; }
        public string CompanyName { get; set; }
        public string TIN { get; set; }
        public string ProductName { get; set; }
        public string Price { get; set; }
    }
}
